# Site settings
title: Pronto! The CfP Helper
email: rafael@doh.ms
description: > # this means to ignore newlines until "baseurl:"
  Pronto is a Chrome Extention that allows speakers to submit their talks 
  to multiple CFPs with the click of a button.
baseurl: "/pronto" # the subpath of your site, e.g. /blog/
url: "http://rdohms.github.io/pronto" # the base hostname & protocol for your site
twitter_username: prontocfp
github_username:  rdohms

# Build settings
markdown: kramdown
exclude: [vendor, package.json, gulpfile.js, Gemfile, Gemfile.lock, src, bower_components, node_modules]
excerpt_separator: <!--more-->
